version: '3.3'

volumes:
    mysql:
        driver: local

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '8000:80'
            - "443:443"
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - ./nginx/www:/var/www/
            - ./nginx/logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/
        links:
            - php
            - redis
            - mysql
    mysql:
        image: mysql:8.0
        restart: "always"
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "33306:3306"
    php:
        build: ./php
        container_name: php
        volumes:
            - ./nginx/www:/var/www
        links:
            - mysql
            - redis
    multithread-loader:
        build: ./multithread-loader
        ports:
            - '8085:80'
        container_name: multithread-loader
    redis:
        image: redis:alpine
        ports:
            - "16379:6379"
        container_name: redis
