version: '3.3'

volumes:
    mysql:
        driver: local

services:
    app:
        build: ./app
        depends_on:
            - mysql
            - redis
        restart: "no"
        ports:
            - "8081:80"
            - "8043:443"
        volumes:
            - ./app:/app
    mysql:
        image: mysql:8.0
        restart: "no"
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'analytics'
    multithread-loader:
        build: ./multithread-loader
        ports:
            - '8085:80'
    redis:
        image: redis:alpine
        ports:
            - "16379:6379"

